services:
  node-app:
    build:
      # context: ./app
      args:
        - NODE_ENV=development
    volumes:
      - ./app:/app
      - /app/node_modules

    environment:
      - NODE_ENV=development
  
    command: npm run dev  

