services:
  node-app:
    build: 
      context: ./app
    # ports:
    #   - "3000:4000"
    environment:
      - PORT=4000
    # restart: always
    depends_on:
      - nginx
  nginx:
    container_name: nginx
    restart: always
    build: 
      context: ./nginx
    ports:
      - "80:80"
